apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    field.cattle.io/publicEndpoints: '[{"addresses":["192.168.10.28"],"port":21570,"protocol":"TCP","serviceName":"dev-gpt-app-base:langfuse-app-nodeport","allNodes":true}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"langfuse-app"},"name":"langfuse-app","namespace":"dev-gpt-app-base"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"langfuse-app"}},"template":{"metadata":{"labels":{"app":"langfuse-app"}},"spec":{"containers":[{"env":[{"name":"NODE_ENV","value":"production"},{"name":"DATABASE_URL","value":"postgresql://gpt_app_user:Gpt_App_User123@192.168.10.26:15432/gpt_app_base_langfuse"},{"name":"NEXTAUTH_URL","value":"http://0.0.0.0:3000"},{"name":"NEXTAUTH_SECRET","value":"LVnS2GXYxfQ9PVYA2GaI1sUGonukKfcm7++FEHywN54="},{"name":"SALT","value":"UISjpL2gmW2KVUo16RXh/AQIG3BuVCqHSE6zj0BuRJ0="},{"name":"TELEMETRY_ENABLED","value":"false"},{"name":"NEXT_PUBLIC_SIGN_UP_DISABLED","value":"false"},{"name":"LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES","value":"false"}],"image":"harborcore.zuoshouyisheng.com/gpt-app-base/langfuse:2.9.0","imagePullPolicy":"Always","name":"langfuse-app","ports":[{"containerPort":3000,"name":"http"}]}]}}}}
  creationTimestamp: "2024-02-27T10:55:43Z"
  generation: 16
  labels:
    app: langfuse-app
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:field.cattle.io/publicEndpoints: {}
    manager: rancher
    operation: Update
    time: "2024-02-27T10:55:43Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:app: {}
          f:spec:
            f:containers:
              k:{"name":"langfuse-app"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"DATABASE_URL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"NEXT_PUBLIC_SIGN_UP_DISABLED"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"NEXTAUTH_SECRET"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"NEXTAUTH_URL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"NODE_ENV"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"SALT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"TELEMETRY_ENABLED"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":3000,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2024-02-27T11:11:06Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2024-05-06T18:02:31Z"
  name: langfuse-app
  namespace: dev-gpt-app-base
  resourceVersion: "745388491"
  uid: 0f89b853-6967-43a1-af19-c268f5047b7f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: langfuse-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: langfuse-app
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: production
        - name: DATABASE_URL
          value: postgresql://gpt_app_user:Gpt_App_User123@192.168.10.26:15432/gpt_app_base_langfuse
        - name: NEXTAUTH_URL
          value: http://0.0.0.0:3000
        - name: NEXTAUTH_SECRET
          value: LVnS2GXYxfQ9PVYA2GaI1sUGonukKfcm7++FEHywN54=
        - name: SALT
          value: UISjpL2gmW2KVUo16RXh/AQIG3BuVCqHSE6zj0BuRJ0=
        - name: TELEMETRY_ENABLED
          value: "false"
        - name: NEXT_PUBLIC_SIGN_UP_DISABLED
          value: "false"
        - name: LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES
          value: "false"
        image: harborcore.zuoshouyisheng.com/gpt-app-base/langfuse:2.9.0
        imagePullPolicy: Always
        name: langfuse-app
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-02-27T10:55:43Z"
    lastUpdateTime: "2024-03-01T03:47:21Z"
    message: ReplicaSet "langfuse-app-67b457cfd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-05-06T18:02:31Z"
    lastUpdateTime: "2024-05-06T18:02:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 16
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
